---
kind: pipeline
name: default

steps:
- name: test
  image: golang:1.12-buster
  group: development
  commands:
    - make install
    - make test
  when:
    event: push

- name: build-publish-release
  image: golang:1.12-buster
  group: production
  environment:
    GITEA_TOKEN:
      from_secret: gitea_token
  commands:
    - git tag $$DRONE_TAG
    - curl -sL https://git.io/goreleaser | bash
  when:
    event: tag
