---
kind: pipeline
name: default

steps:
- name: test
  image: golang:1.13.1-buster
  group: development
  commands:
    - make install
    - make test
  when:
    event: push

- name: build-publish-release
  image: golang:1.13.1-buster
  group: production
  environment:
    GITEA_TOKEN:
      from_secret: gitea_token
  commands:
    - make prod.release.ci
  when:
    event: tag
