project_name: go-tspath
dist: bin
build:
  main: go-tspath.go
  binary: go-tspath
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
sign:
  cmd: gpg
  args:
  - --output
  - $signature
  - --detach-sig
  - $artifact
  signature: ${artifact}.sig
  artifacts: none
env_files:
  github_token: ~/.config/goreleaser/github_token
snapshot:
  name_template: "{{ .Tag }}-next"
