project_name: go-tspath
release:
  name_template: '{{.Tag}}'
# brew:
#   name: go-tspath
#   commit_author:
#     name: goreleaserbot
#     email: goreleaser@carlosbecker.com
#   install: bin.install "go-tspath"
# scoop:
#   name: go-tspath
#   commit_author:
#     name: goreleaserbot
#     email: goreleaser@carlosbecker.com
#   url_template: https://github.com///releases/download/{{ .Tag }}/{{ .ArtifactName
#     }}
builds:
- id: go-tspath
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  goarm:
  - "6"
  targets:
  - linux_amd64
  - darwin_amd64
  main: .
  ldflags:
  - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: go-tspath
  env:
  - CGO_ENABLED=0
  lang: go
archives:
- id: default
  builds:
  - go-tspath
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  replacements:
    amd64: x86_64
    darwin: Darwin
    linux: Linux
    windows: Windows
  format: tar.gz
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
nfpm:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  bindir: /usr/local/bin
snapcraft:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
snapshot:
  name_template: '{{ .Tag }}-next'
checksum:
  name_template: checksums.txt
  algorithm: sha256
changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
  sort: asc
dist: bin
sign:
  cmd: gpg
  args:
  - --output
  - $signature
  - --detach-sig
  - $artifact
  signature: ${artifact}.sig
  artifacts: none
env_files:
  github_token: ~/.config/goreleaser/github_token
before:
  hooks:
  - go mod download
  - go generate ./...
github_urls:
  download: https://github.com
