settings:
  legacy:
    force: false
    interval: 100s
schema:
- name: go-tspath
  path: .
  args:
    - -config=./sample/tsconfig.replace.json
  commands:
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
