[[constraint]]
  branch = "master"
  name = "github.com/joseluisq/go-tspath"

[[constraint]]
  name = "github.com/mattn/go-zglob"
  version = "0.0.1"

[prune]
  go-tests = true
  unused-packages = true
